version: "1.0"

services:
  frontend:
    build: ./app/frontend
    volumes:
      - ./app/frontend:/frontend
      - /frontend/node_modules
      - /frontend/dist
    ports:
      - 3000:3000
    container_name: frontend
  backend:
    env_file: ./app/backend/.env.develop
    build: ./app/backend
    volumes:
      - ./app/backend:/backend
      - /backend/node_modules
    ports:
      - 5000:5000
    container_name: backend
    depends_on:
      - db
  db:
    image: postgres:15.3
    container_name: db
    env_file:
      - .env.db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
  db-test:
    image: postgres:15.3
    container_name: db-test
    env_file:
      - .env.db.test
    ports:
      - 5434:5432
