services:
  controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
  controllers.MessagePutController:
    class: ../../controllers/message/MessagePutController
    arguments: ['@application.MessageCreator']
