services:
  controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []
  controllers.MessagePutController:
    class: ../../controllers/message/MessagePutController
    arguments: ['@application.MessageCreator']
  controllers.MessagesGetController:
    class: ../../controllers/message/MessagesGetController
    arguments: ['@application.MessagesRetrieve']
  controllers.MessageDeleteController:
    class: ../../controllers/message/MessageDeleteController
    arguments: ['@application.MessageDelete']
